### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by selva070** [moemoe89/twitter-login-ci3#1]
I'm not familiar with OAuth so I'm not able to figure out what is going bad with the library. I will try to fix this.

The complete error was:

A PHP Error was encountered
Severity: Notice
Message: Undefined index: oauth_token
Filename: libraries/twconnect.php
Line Number: 126

**Comment by moemoe89** [comment]
do you have register app on twitter ?  make sure you've have Consumer Key (API Key) & Consumer Secret (API Secret)

**Comment by selva070** [comment]
ya i have registered and added consumer key & secret ket but still get error.

**Comment by moemoe89** [comment]
do you run on localhost ? or on server

**Comment by selva070** [comment]
Run on the server..

**Comment by moemoe89** [comment]
i've no idea , because i just try again, download the file, upload to my server, setting config twitter and i can run it..how about on localhost ? do you try it ?

**Comment by selva070** [comment]
I will check it once and revert you asap.

**Comment by moemoe89** [comment]
sure..let notify me if you've done

**Comment by selva070** [comment]
Hi,
can you check this Url:
http://selva070.me/code/

all the settings are correct but gets error.

**Comment by selva070** [comment]
in twitter.php what is the 
'oauth_callback'  => '' // Default callback application path 
i have to specify?

**Comment by moemoe89** [comment]
yes, you must specify it.. because on Welcome controller, i have write callback function

this is the important script for callback : 
$this->twconnect->twprocess_callback();

you can find in my demo on Welcome controller, callback function line 40

so on config -> twitter.php i've define like this : 
'oauth_callback'  => '/welcome/callback'

**Comment by selva070** [comment]
Hi
The Issue has been solved. My callback URL in the application settings is the issue.

Thanks
